# Image Python resmi sebagai base image
FROM python:3.10-slim

# Direktori kerja dalam kontainer
WORKDIR /app

# Salin file requirements.txt ke direktori kerja
COPY requirements.txt .

# Instal dependensi Python
RUN pip install --no-cache-dir -r requirements.txt

# Salin seluruh isi direktori lokal ke direktori kerja container
COPY . .

# Port FastAPI
EXPOSE 8000

# Run app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]